### ISSUE TITLE
[ENHANCEMENT] (Not of Priority) Add Dark Mode

### ISSUE THREAD

**Issue by eshaane** [SkylineSpartabots/SpartaSite#15]
Many people hate light mode, as do i, this is why Dark Mode should be an option, this is primarily CSS tweaks, very minor JS. The idea is to have a toggle which is either a button or a switch that switches between light and dark modes, to store current status set up a cookie or browser cache.

**Comment by mohit-bhandari45** [comment]
I want to work on this issue under gssoc24
Just add the label of gssoc24 to it
Assign it to me

**Comment by eshaane** [comment]
done

**Comment by eshaane** [comment]
@mohit-bhandari45 when can this be worked on?

**Comment by mohit-bhandari45** [comment]
Tomorrow I will make a PR

**Comment by eshaane** [comment]
@mohit-bhandari45 sounds good please let me know once pr is submitted

**Comment by mohit-bhandari45** [comment]
I want to ask, are you in gssoc 24?

**Comment by eshaane** [comment]
> I want to ask, are you in gssoc 24?

I do not believe we are

**Comment by mohit-bhandari45** [comment]
Ok no problem
But I think you can still add "gssoc24" and "level2" labels to it

**Comment by eshaane** [comment]
to the issue?

**Comment by mohit-bhandari45** [comment]
Yup

**Comment by mohit-bhandari45** [comment]
It's your choice btw, not necessary

**Comment by eshaane** [comment]
yea i gottchu doin rn

**Comment by mohit-bhandari45** [comment]
Ok ok perfect

**Comment by eshaane** [comment]
done, let me know once pr created

**Comment by mohit-bhandari45** [comment]
Are these cards looking good in dark mode?
![image](https://github.com/SkylineSpartabots/SpartaSite/assets/151373021/4af2226a-30cb-4379-bda9-8b2d63604f29)
![image](https://github.com/SkylineSpartabots/SpartaSite/assets/151373021/6ea681df-a45f-45b3-aef8-64606ff3ac22)

**Comment by eshaane** [comment]
> Are these cards looking good in dark mode?
> ![image](https://github.com/SkylineSpartabots/SpartaSite/assets/151373021/4af2226a-30cb-4379-bda9-8b2d63604f29)
> ![image](https://github.com/SkylineSpartabots/SpartaSite/assets/151373021/6ea681df-a45f-45b3-aef8-64606ff3ac22)
> 
> 

They look ok, I'd also try the black #1f1f1f. Also, can you round the cards a slight bit so it isn't sharp corners. One more thing is there needs to be the toggle, for the toggle I'd like for it to float on the bottom right throughout the site. Thanks!

**Comment by mohit-bhandari45** [comment]
Hey I have done the home section

Just tell me is the background color where there are cards is good or what.
I not you can give me the hax codes of you color theme
![image](https://github.com/SkylineSpartabots/SpartaSite/assets/151373021/3c1547c6-a09d-4389-9b1f-fc40dc5d12d7)

This is the second preview one:-
![image](https://github.com/SkylineSpartabots/SpartaSite/assets/151373021/46f75c01-8cd4-43d3-b5c7-3a0b56d80b59)

Which one is looking good

**Comment by eshaane** [comment]
2nd one looks the best, lets go with that one

**Comment by mohit-bhandari45** [comment]
I have created a pr, you can check

**Comment by eshaane** [comment]
Perfect, Thank you @mohit-bhandari45, i was wondering if you were able to push the same changes to these files, they are not currently being used but will setup in the near future.
"./pages/ComingSoon"
"./pages/Login"
"./pages/NotFound"
"./pages/OurTeam"
"./pages/HistoryPage"
"./pages/Purchase"
"./pages/Software"

**Comment by mohit-bhandari45** [comment]
Hey bro can we connect?
This is y linkedin:
https://www.linkedin.com/in/mohit-bhandari-9940542a0/

**Comment by mohit-bhandari45** [comment]
> Perfect, Thank you @mohit-bhandari45, i was wondering if you were able to push the same changes to these files, they are not currently being used but will setup in the near future. "./pages/ComingSoon" "./pages/Login" "./pages/NotFound" "./pages/OurTeam" "./pages/HistoryPage" "./pages/Purchase" "./pages/Software"

Sure!

**Comment by eshaane** [comment]
> Hey bro can we connect? This is y linkedin: https://www.linkedin.com/in/mohit-bhandari-9940542a0/



> > Perfect, Thank you @mohit-bhandari45, i was wondering if you were able to push the same changes to these files, they are not currently being used but will setup in the near future. "./pages/ComingSoon" "./pages/Login" "./pages/NotFound" "./pages/OurTeam" "./pages/HistoryPage" "./pages/Purchase" "./pages/Software"
> 
> Sure!

Connected! and thank you so much

**Comment by mohit-bhandari45** [comment]
> > Hey bro can we connect? This is y linkedin: https://www.linkedin.com/in/mohit-bhandari-9940542a0/
> 
> > > Perfect, Thank you @mohit-bhandari45, i was wondering if you were able to push the same changes to these files, they are not currently being used but will setup in the near future. "./pages/ComingSoon" "./pages/Login" "./pages/NotFound" "./pages/OurTeam" "./pages/HistoryPage" "./pages/Purchase" "./pages/Software"
> > 
> > 
> > Sure!
> 
> Connected! and thank you so much

Perfect!

**Comment by eshaane** [comment]
Some issues i have noticed on the current dark mode setup are as follows:
- The toggle is very broken on mobile screens, the fix id like is a floating toggle that is always on the bottom left side regardless of the page/screen size
- In smaller screen sizes i noticed the bottom panel "Our Sponsors, etc." turns back to white.

![image](https://github.com/SkylineSpartabots/SpartaSite/assets/84348006/f2ef817d-928a-4855-83d2-faac4834b2e8)
![image](https://github.com/SkylineSpartabots/SpartaSite/assets/84348006/7f8dbabe-a636-4229-aa81-ea338558c5b4)

**Comment by mohit-bhandari45** [comment]
Yeah sure for mobile screen, I can work upon it.
Do are you making a separate issue for it or work on it right here?

**Comment by eshaane** [comment]
you can work on it right here it should be fine

**Comment by mohit-bhandari45** [comment]
and bro the second, issue is bcoz, the cards are different for mobile view, I didn't know it.
I will fix it

**Comment by mohit-bhandari45** [comment]
bro created a pr, you can check

**Comment by eshaane** [comment]
thanks for the pr!
