### ISSUE TITLE
[BUG] (URGENT) {ASSIGNED} Mobile UI is VERY Broken

### ISSUE THREAD

**Issue by eshaane** [SkylineSpartabots/SpartaSite#16]
We need to fix mobile UI, primarily the Splash/Text on each part of the website. This is primarily HTML/CSS with minor JS. 2 current issues are one being the Splash and the 2nd being the navbar, when a mobile Screen Size is detected the Navbar should turn into the Sidebar that we have made, although the Sidebar was also made for desktop so it needs to be tweaked to fit mobile screens.

**Comment by Sky-De** [comment]
@Gam3rrXD hi there, i would like to take a look and improve it, please assign this to me, thanks

**Comment by eshaane** [comment]
sounds good

**Comment by Sky-De** [comment]
@Gam3rrXD There appears to be a responsiveness issue in multiple routes. , Either those routes that have a link in the navigation or other routes like : /fontDemo, /about, /ourteam, /purchase, /software and ... 

Would it be okay if I fix each issue one by one and create separate pull requests for each change on daily basis? This will make it easier to review the code and test each part individually for responsiveness.
inform me about it please, 
Also i provide some gifs of issue on route that exists in nav

### Show Case ( wait for load )
<div>
<img src="https://github.com/SkylineSpartabots/SpartaSite/assets/79264045/0adc7fe7-04d3-48fe-9c30-d71c524572a8"  width="20%" />
<img src="https://github.com/SkylineSpartabots/SpartaSite/assets/79264045/22a48507-4593-44c8-a5b3-bf8728e0f0e8"  width="20%" />
<img src="https://github.com/SkylineSpartabots/SpartaSite/assets/79264045/57852991-69f9-4877-a88c-662347caca08"  width="20%" />
<img src="https://github.com/SkylineSpartabots/SpartaSite/assets/79264045/6e5abea3-b98e-48fa-b57c-413001fddf4a"  width="20%" />
</div>

**Comment by eshaane** [comment]
@Sky-De hi there, this sounds good. some of these endpoints such as /fontDemo are for testing/development purposes so these aren't production issues, everything else is a production issue. as far as the navigation as mentioned in the original issue id like it to use the Sidebar.js. Pull requests are fine, all I need is some sort of indication of what was fixed, I can merge on a daily basis after reviewing each. Thank you!

**Comment by Sky-De** [comment]
@Gam3rrXD ok then, Thank you for your prompt response. I will start by making the nav bar and main page responsive and creating a pull request for that tonight. Afterward, I will work on the other pages one by one every day till the entire app is responsive.

**Comment by eshaane** [comment]
@Sky-De that sounds perfect, thank you again :)

**Comment by eshaane** [comment]
![image](https://github.com/SkylineSpartabots/SpartaSite/assets/84348006/e1aade21-e5cf-45c0-8141-6a0a9aa6a5bb)
is there anyway to have this text to the left hand side? I tried modifying the text-center part but it doesn't look correct, this is on the mobile ui

**Comment by Sky-De** [comment]
> ![image](https://private-user-images.githubusercontent.com/84348006/329872908-e1aade21-e5cf-45c0-8141-6a0a9aa6a5bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NDA4NTAsIm5iZiI6MTcxNTU0MDU1MCwicGF0aCI6Ii84NDM0ODAwNi8zMjk4NzI5MDgtZTFhYWRlMjEtZTVjZi00NWMwLTgxNDEtNmEwYTlhYTZhNWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEyVDE5MDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZGI4ZjRlNjg4NjNhYTMxZTNlMDk3ZWQwMjEwNjQwZjhiZjI5ZmRiNDAyNTM0NmM5NzlkMzNmYTYyNThkNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nYyPCiAGUgdrePbSAfY85tpOceUyinQ8RR5A6_96LZo) is there anyway to have this text to the left hand side? I tried modifying the text-center part but it doesn't look correct, this is on the mobile ui

@Gam3rrXD sure, in upcoming PR i will fix that too!

**Comment by eshaane** [comment]
thank you!

**Comment by eggliot** [comment]
I just noticed when you open the hamburger menu the transition is quite jarring between the new menu and page behind it. 
Maybe make the blur background take up the whole screen. 
![image](https://github.com/SkylineSpartabots/SpartaSite/assets/107228567/e5bd0478-670c-4495-97c7-28fecc76845d)

**Comment by mohit-bhandari45** [comment]
I want to work on the hamburger issue.
Instead I can make a transition of right to left and left to right in hamburger.
Assign it to me under gssoc24

**Comment by eshaane** [comment]
> I want to work on the hamburger issue. Instead I can make a transition of right to left and left to right in hamburger. Assign it to me under gssoc24

sounds good, thank you!

**Comment by eshaane** [comment]
A new issue will be opened for the hamburger menu, mobile responsiveness has been resolved!
