### ISSUE TITLE
[ENHANCEMENT] (ASAP) {ASSIGNED} Fix Hamburger Menu

### ISSUE THREAD

**Issue by eshaane** [SkylineSpartabots/SpartaSite#22]
I just noticed when you open the hamburger menu the transition is quite jarring between the new menu and page behind it. 
Maybe make the blur background take up the whole screen. 
![image](https://github.com/SkylineSpartabots/SpartaSite/assets/107228567/e5bd0478-670c-4495-97c7-28fecc76845d)

_Originally posted by @messier81porcupine in https://github.com/SkylineSpartabots/SpartaSite/issues/16#issuecomment-2108759554_
            

This issue has been ASSIGNED

**Comment by eshaane** [comment]
@mohit-bhandari45 this is the issue, submit your PR's here

**Comment by Sky-De** [comment]
@Gam3rrXD Hi again, I can not see what was the reason for creating this issue, was there anything wrong with the current mobile menu?
if there is explain it to me ( why? ) then assign it to me since it is not assigned to anyone else
thanks

**Comment by eshaane** [comment]
> @Gam3rrXD Hi again, I can not see what was the reason for creating this issue, was there anything wrong with the current mobile menu?
> if there is explain it to me ( why? ) then assign it to me since it is not assigned to anyone else
> thanks

Oh yea sorry, in the original issue one of my colleagues mentioned that there was some animation issue and he wanted it full screened, I saw that u submitted your last pr for that issue and since this issue wasn't as big I jus made it a new issue, sorry for no heads up.

**Comment by mohit-bhandari45** [comment]
I created a PR, you can check

**Comment by eshaane** [comment]
> I created a PR, you can check

Yes I just saw, I will test on my end then merge, thanks!

**Comment by eshaane** [comment]
@Sky-De you can still work on this issue if you feel like it, the provided solution us not what we are looking for.

**Comment by Sky-De** [comment]
> @Sky-De you can still work on this issue if you feel like it, the provided solution us not what we are looking for.

@Gam3rrXD hey, what exactly do you want? Full screen menu with solid background? No transition? Explain what exactly makes this menu as well as you want, thanks

**Comment by Sky-De** [comment]
@Gam3rrXD Hi, may I ask you a favor? I'd appreciate it if you could take a look at my [Portfolio ](https://skyde-portfolio.netlify.app/)and other projects. Please let me know what you think about them, and if you like them, please give them a STAR. All public projects can be found in the PROJECTS section of my portfolio. Within that section, you can find live demo links as well as repository links related to each project.And if you like my project please mention other colleagues of these projects here to check my [Portfolio ](https://skyde-portfolio.netlify.app/), thanks thanks

**Comment by mohit-bhandari45** [comment]
Hey @Gam3rrXD, do you want this??
![image](https://github.com/SkylineSpartabots/SpartaSite/assets/151373021/d3d98b23-582f-463e-8fba-e92b37eff451)


It is full screen, btw for every screen size!

**Comment by eshaane** [comment]
> Hey @Gam3rrXD, do you want this??
> ![image](https://github.com/SkylineSpartabots/SpartaSite/assets/151373021/d3d98b23-582f-463e-8fba-e92b37eff451)
> 
> 
> It is full screen, btw for every screen size!

Hi there,  yes this is pretty much what I'm looking for, it should only apply to mobile scrensizes, any desktop screen sizes utilize the topbar

**Comment by mohit-bhandari45** [comment]
Yes it is like that for mobiles

**Comment by mohit-bhandari45** [comment]
Ok i have done it.
Are you a part of gssoc24?
If yes just add two labels "gssoc24" and "level2" to it and remove the gssoc24(mohit)

**Comment by mohit-bhandari45** [comment]
Hey I created a PR, related to this.
Please check it.

**Comment by eshaane** [comment]
Works perfectly
